Carbon:
  IncludeAssets:
    Path:
      Inline:
        CSS: 'Public/Frontend'
        JS: 'Public/Frontend'
      File:
        CSS: 'Public/Frontend'
        JS: 'Public/Frontend'
    General:
      Head:
        -Main.css
      Body:
        -Main.js
